export const USER_PREFERRED_CURRENCY = '@TronWallet:userPreferredCurrency'
export const USER_PREFERRED_LANGUAGE = '@TronWallet:userPreferredLanguage'
export const USER_STATUS = '@TronWallet:useStatus'
export const ADD = 'ADD'
export const EDIT = 'EDIT'
export const USER_FILTERED_TOKENS = '@TronWallet:userFilteredTokens'
